### ISSUE TITLE
ksampler with refiner (fooocus)

### ISSUE THREAD

**Issue by rossaai** [pydn/ComfyUI-to-Python-Extension#10]
```
  File "C:\Users\Usuario\Documents\Git Clone\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 246, in generate_workflow
    final_code = self.assemble_python_code(import_statements, special_functions_code, code, queue_size, custom_nodes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Documents\Git Clone\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 328, in assemble_python_code
    final_code = black.format_str(final_code, mode=black.Mode())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\black\__init__.py", line 1085, in format_str
  File "src\black\__init__.py", line 1095, in _format_str_once
  File "src\black\parsing.py", line 100, in lib2to3_parse
black.parsing.InvalidInput: Cannot parse: 112:11:               ksampler with refiner (fooocus) = NODE_CLASS_MAPPINGS["KSampler With Refiner (Fooocus)"]()
```

The extension
[ComfyUI_Fooocus_KSampler](https://github.com/hustille/ComfyUI_Fooocus_KSampler)

<img width="972" alt="image" src="https://github.com/pydn/ComfyUI-to-Python-Extension/assets/132106533/a0e139fc-455e-4b0d-8de5-85f4112938b7">

This is the workflow im using (rename it to .json. Github dont support upload .json)
[workflow.txt](https://github.com/pydn/ComfyUI-to-Python-Extension/files/12420317/workflow.txt)

**Comment by pydn** [comment]
I think this is related to this issue https://github.com/pydn/ComfyUI-to-Python-Extension/issues/8

I'll take a look at this and circle back when the hotfix is ready.

**Comment by rossaai** [comment]
Probably the is the use of `ksampler with refiner (fooocus)` is not posible to instance it as a variable name.

[ComfyUI_Fooocus_KSampler/blob/main/__init__.py#L4](https://github.com/hustille/ComfyUI_Fooocus_KSampler/blob/main/__init__.py#L4)
```python
# ComfyUI/custom_nodes/ComfyUI_Fooocus_KSampler/__init__.py#L4
NODE_CLASS_MAPPINGS = {
    "KSampler With Refiner (Fooocus)": KSamplerWithRefiner,
}
```

**Comment by rossaai** [comment]
I'll open a pull request soon

**Comment by pydn** [comment]
Just pushed the update to main with the hotfix. Thank you for your help!
