### ISSUE TITLE
This fail to generate for controlnet sdxl workflow

### ISSUE THREAD

**Issue by MaxTran96** [pydn/ComfyUI-to-Python-Extension#13]
Total VRAM 45591 MB, total RAM 64139 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX 6000 Ada Generation : native
Using xformers cross attention
Traceback (most recent call last):
  File "/workspace/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 439, in <module>
    ComfyUItoPython(input_file=input_file, output_file=output_file, queue_size=queue_size)
  File "/workspace/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 404, in __init__
    self.execute()
  File "/workspace/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 420, in execute
    load_order = load_order_determiner.determine_load_order()
  File "/workspace/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 123, in determine_load_order
    self._load_special_functions_first()
  File "/workspace/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 159, in _load_special_functions_first
    class_def = self.node_class_mappings[self.data[key]['class_type']]()
TypeError: 'int' object is not subscriptable

I got these workflows from

https://huggingface.co/stabilityai/control-lora/tree/main/comfy-control-LoRA-workflows

**Comment by pydn** [comment]
Did you export in API format from ComfyUI?

**Comment by MaxTran96** [comment]
yes

**Comment by pydn** [comment]
Hmm I'd have to see the workflow_api.json file and version of ComyUI to Python Extension you were using to see if I can recreate the issue.

**Comment by pydn** [comment]
Closing this for now since I haven't heard back, but feel free to reopen if you are still having trouble here.

**Comment by madriss** [comment]
Having the same issue with this workflow. If someone could take a look that would be much helpful. 
[qrcode_mask_workflow.json](https://github.com/pydn/ComfyUI-to-Python-Extension/files/13435194/qrcode_mask_workflow.json)

**Comment by danyow-cheung** [comment]
> ###
> **[madriss](/madriss) ** commented [Nov 22, 2023](#issuecomment-1822291952)

Because you  saved the wrong json file ,the correct json file should be like below . Remember to follow the instructions in the readme.md 
> Launch ComfyUI, click the gear icon over Queue Prompt, then check Enable Dev mode Options. THE SCRIPT WILL NOT WORK IF YOU DO NOT ENABLE THIS OPTION! 

![image](https://github.com/pydn/ComfyUI-to-Python-Extension/assets/76671016/873dc141-7081-4cc4-9c68-df975d4fce31)
