### ISSUE TITLE
no module named utils

### ISSUE THREAD

**Issue by JBowen99** [pydn/ComfyUI-to-Python-Extension#14]
When running the script, I always get this issue. Not sure what utils module the code is trying to load

Traceback (most recent call last):
  File "C:\...\ComfyUI-to-Python-Extension-main\comfyui_to_python.py", line 14, in <module>
    from utils import import_custom_nodes, find_path, add_comfyui_directory_to_sys_path, add_extra_model_paths, get_value_at_index
ModuleNotFoundError: No module named 'utils'

**Comment by pydn** [comment]
Make sure you navigate to the ComfyUI-to-Python-Extension directory in your terminal before running comfyui_to_python.py. the script looks in the current working directory for utils.py.

**Comment by JBowen99** [comment]
I see. Thank you.
