### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by EvotisLab** [pydn/ComfyUI-to-Python-Extension#17]
Hi pydn,
I love what you've done and I'd like to contribute.
Are you open to pull resquests?

**Comment by pydn** [comment]
Hey, thanks for your interest! What changes did you have in mind?

**Comment by EvotisLab** [comment]
Parse input/output as arguments instead of having to change the code, like so:

`
"""
Use it like that:
python comfyui_to_python.py -i ../workflows-api/some_wf_api
"""
import sys
import argparse as argparse
parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                    description=__doc__,
                                    epilog=__doc__)
parser.add_argument("-i", "--input", type=str, action="store", default="workflow_api",
                    help="name of the input workflow api json, without the .json extension")
parser.add_argument("-o", "--output", type=str, action="store",
                    help="name of the output workflow script, without the .py extension, falls back on the input name if not provided")
parser.add_argument("-b", "--batch-size", type=int, action="store", default=1,
                    help="batch size applied in the generated script")
args = parser.parse_args()
`

**Comment by pydn** [comment]
I think that would be a great change, but my planned next step is to create an export button directly from ComfyUI to streamline the script generation process so I don't think cli args would be needed in that case. 

The other challenge is that arguments already get parsed when anything from nodes.py is imported which presents a new challenge for adding additional cli arguments.

**Comment by Mamba-ZJP** [comment]
So this means the pipeline is fixed once ComfyUI converted to python? I cannot add input image path to this pipeline.py by using arg_parser?

**Comment by hanruishiren** [comment]
> I think that would be a great change, but my planned next step is to create an export button directly from ComfyUI to streamline the script generation process so I don't think cli args would be needed in that case.
> 
> The other challenge is that arguments already get parsed when anything from nodes.py is imported which presents a new challenge for adding additional cli arguments in this script.

I found it too  :(
I tried the normal way for args and add_subparsers way, but neither works.

**Comment by RickDT** [comment]
Fwiw, I found that if I'm using an exported script in another script which has incompatible argv args, I can just reset argv before importing the script:

```python
sys.argv = [""]
from workflow_api import main
```
