### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by RobertoLando** [pydn/ComfyUI-to-Python-Extension#18]
I'm using a few generated scripts on an EC2 instance of type g4dn.xlarge, with Tesla T4 GPU

When running the workflow from the ComfyUI interface, I see traced in logs:
  `Device: cuda:0 Tesla T4 : cudaMallocAsync`
while if I run the generated python script I see:
  `Device: cuda:0 Tesla T4 : native`

The script produces similar result, but it's a lot slower. I tryied to add `--cuda-malloc` to the command line, but nothing changes. Any clue?

btw: great extension!

**Comment by RobertoLando** [comment]
Found a solution: in the python script generated by this extension you need to add import `cuda_malloc` at the beginning (with some code to verify if it is supported) and move the `import torch` statement from the beginning to the first line after `def main():`

It would be useful to generate code already in this form

**Comment by min-star** [comment]
> Found a solution: in the python script generated by this extension you need to add import `cuda_malloc` at the beginning (with some code to verify if it is supported) and move the `import torch` statement from the beginning to the first line after `def main():`
> 
> It would be useful to generate code already in this form

i add the code,but the cost time is same with not add
