### ISSUE TITLE
how to pass argument in inference for example --cpu

### ISSUE THREAD

**Issue by maxixa** [pydn/ComfyUI-to-Python-Extension#23]

**Comment by someghuser** [comment]
`RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

It shouldn't need a gpu to generate code. Use case: using cloud gpu to generate images.

**Comment by pydn** [comment]
Have you tried `python workflow_api.py --cpu` ?

**Comment by thigazholi** [comment]
Do we need GPU to run comfyui_to_python.py?

**Comment by atmaranto** [comment]
You shouldn't need a GPU, but it'll be _slow_ without one.
