### ISSUE TITLE
Question RE use case

### ISSUE THREAD

**Issue by aegis72** [pydn/ComfyUI-to-Python-Extension#24]
Could this be used to effectively write a custom node (more or less)? For instance, in my AegisFlow workflow, I have a large image saving section that really doesn't need exposed; I'd rather have the user just have in some inputs to fill in and have the rest of the image saving process happen as a single node. I previously used a custom node called "ComponentBuilder" that can do this, but unfortunately when plugins get updated it all breaks, and can't be easily untangled again so I abandoned that approach.

But if I could make my own node, maybe I could control the process a bit better.

**Comment by pydn** [comment]
This library is not really meant to be used to help write custom nodes. However, you could modify the output script as you wish once it's generated, which could include any custom process you can think of.
