### ISSUE TITLE
result with noise

### ISSUE THREAD

**Issue by lvZic** [pydn/ComfyUI-to-Python-Extension#25]
I just used the code in your repo with 
![image](https://github.com/pydn/ComfyUI-to-Python-Extension/assets/7788572/1e9f1ccc-9e6d-4455-989c-c51a4dd962e8)

however, the generated result is filled with noise. I wonder why?
![image](https://github.com/pydn/ComfyUI-to-Python-Extension/assets/7788572/59c688e0-1cf9-452f-bc51-580162abbd29)

**Comment by pydn** [comment]
Did you test your workflow in ComfyUI before running it with this extension?

**Comment by lvZic** [comment]
> Did you test your workflow in ComfyUI before running it with this extension?

this problem is about the sdxl-base.1.0 model.
