### ISSUE TITLE
Problem on custom node  VideoHelperSuite

### ISSUE THREAD

**Issue by HanJu-Chen** [pydn/ComfyUI-to-Python-Extension#33]
I'm trying to convert my workflow to code, but when I run to the combine vedio section, this error occurs.
![微信截图_20240103165217](https://github.com/pydn/ComfyUI-to-Python-Extension/assets/96210358/4135f6f8-9ce4-4188-9c5e-7eceb492e044)
My workflow works fine in comfyui but fails in python.

**Comment by HanJu-Chen** [comment]
[workflow_api.json.txt](https://github.com/pydn/ComfyUI-to-Python-Extension/files/13817211/workflow_api.json.txt)
[workflow_api.py.txt.txt](https://github.com/pydn/ComfyUI-to-Python-Extension/files/13817212/workflow_api.py.txt.txt)
This is my workflow and code.

**Comment by HanJu-Chen** [comment]
There was a conflict when the VHS module was running, when I removed the VHS module and replaced it with the image saving module, it worked.

**Comment by YacratesWyh** [comment]
You can save in setting debug in official right now, don't have to use this repo

**Comment by poisenbery** [comment]
I believe this might be a similar issue to https://github.com/pydn/ComfyUI-to-Python-Extension/issues/32 and https://github.com/pydn/ComfyUI-to-Python-Extension/issues/26

It seems that some arguments are not being passed for certain custom nodes.
