### ISSUE TITLE
Nodes seems to be deprecated.

### ISSUE THREAD

**Issue by ChrisFlick** [pydn/ComfyUI-to-Python-Extension#4]
Can't seem to install nodes and comfyui_to_python.py requires it. wondering if there's a work around here.

**Comment by pydn** [comment]
The nodes module comes from the ComfyUI repo. Be sure to clone the repo directly into your ComfyUI folder. Check out installation step 2.

**Comment by pydn** [comment]
I'm going to close this issue for now since I'm assuming my response addresses your question. Feel free to reopen if you have further questions!
