### ISSUE TITLE
A fixed-seed value and specifier are disregarded

### ISSUE THREAD

**Issue by lutusp** [pydn/ComfyUI-to-Python-Extension#42]
While converting a KSampler control that specifies a fixed seed value, this extension's code always creates:

`seed=random.randint(1, 2**64)`

... regardless of the provided seed value and the "fixed" specifier in the "control_after_generate" field.

This issue comes up while creating a series of images that use a "ConditioningAverage" control to morph between two text descriptions. If the original seed value is manually entered instead of `random.randint(1, 2**64)`, the code works as expected.

**Comment by atmaranto** [comment]
Unfortunately, this was likely originally implemented to conform to the most common usage of KSampler to generate different images. In [my fork](https://github.com/atmaranto/ComfyUI-SaveAsScript), I added a way to pass values as command-like args in the exported `.py` file, but there isn't currently a good way to set a seed.

The best way I can think of would be to create a set seed would be to use a Primitive node that is _not_ the vanilla ComfyUI primitive (which is simplified in the export to a value), set it to the value you want, and connect it to the seed for KSampler.

Here's what I mean:
![workflow (1)](https://github.com/pydn/ComfyUI-to-Python-Extension/assets/35581227/7801779c-ce09-4dac-a58f-74a2dfffec54)
This uses the Primitive Integer from Crystools.
