### ISSUE TITLE
Works on GUI but fails in the script. something with Image1 kwargs

### ISSUE THREAD

**Issue by blademarketing** [pydn/ComfyUI-to-Python-Extension#45]
I have a super simple workflow that takes 3 images, feeds them into ip adapter and generates an image, then upsacles it.

Works fine on GUI
Here is the original workflow
[test.json](https://github.com/pydn/ComfyUI-to-Python-Extension/files/14886307/test.json)

It succesfully compiled it into a .py script and then when i run it with python i get this:

`model_type EPS
adm 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
clip unexpected: ['clip_l.transformer.text_model.embeddings.position_ids']
Requested to load SD1ClipModel
Loading 1 new model
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
Leftover VAE keys ['model_ema.decay', 'model_ema.num_updates']
INFO: Clip Vision model loaded from C:\ComfyUI\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
INFO: IPAdapter model loaded from C:\ComfyUI\ComfyUI\models\ipadapter\ip-adapter-faceid-plusv2_sd15.bin
INFO: LoRA model loaded from C:\ComfyUI\ComfyUI\models\loras\ip-adapter-faceid-plusv2_sd15_lora.safetensors
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
INFO: InsightFace model loaded with CPU provider
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\ComfyUI-to-Python-Extension\workflow_api.py", line 291, in <module>
    main()
  File "C:\ComfyUI\ComfyUI\ComfyUI-to-Python-Extension\workflow_api.py", line 210, in main
    impactmakeimagebatch_32 = impactmakeimagebatch.doit()
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\util_nodes.py", line 378, in doit
    image1 = kwargs['image1']
KeyError: 'image1'

`C:\ComfyUI\ComfyUI\ComfyUI-to-Python-Extension>``

**Comment by blademarketing** [comment]
Made this video just to give you a clearer insight @pydn 
https://www.loom.com/share/d5ec93d744c544649847cdaf78f014a8

**Comment by atmaranto** [comment]
This issue [may be fixed on my fork](https://github.com/atmaranto/ComfyUI-SaveAsScript).
Kwargs is now sent if requested by the function.

**Comment by pydn** [comment]
@blademarketing I made a few updates the last couple of days that may fix this issue so feel free to pull the latest version and check the output. If you are still running into issues, feel free to reopen this ticket
