### ISSUE TITLE
QUESTION: can't save workflow_api.json if I upload a comfyui template

### ISSUE THREAD

**Issue by athreesh** [pydn/ComfyUI-to-Python-Extension#50]
New to comfyUI, launched comfyUI thru a jupyter notebook on a GPU VM. Save (API format) works for the default template and I'm able to download a .json. But I dragged a template .png I found on CivitAI to ComfyUI and the .json download for workflow_api.json doesn't actually download. Anything I'm doing wrong?

**Comment by atmaranto** [comment]
It could be there's some sort of issue -- you might need to post your JavaScript console logs for help. You could also try [my fork](https://github.com/atmaranto/ComfyUI-SaveAsScript), which is a bit more consistent, but YMMV.

**Comment by pydn** [comment]
@athreesh That sounds like an issue outside of this extension if the error is coming from simply downloading the workflow_api.json from the comfyui web app.
