### ISSUE TITLE
how can I use this script with existing ComfyUI

### ISSUE THREAD

**Issue by sekomer** [pydn/ComfyUI-to-Python-Extension#58]
I don't want to load / initialize all models again from start when I run the script, I want to initialize the model, and use it as an endpoint, with fastapi or something like that. 

I moved the following sections to upwards, but it doesn't changed anything
 
NODE_CLASS_MAPPINGS["VAEEncode"]()

how can I achieve this?

**Comment by pydn** [comment]
To achieve what you are looking for would require some additional updates to the generated output that is currently out of scope for this repo, but I think the generated script should give you a great head start
