### ISSUE TITLE
Fix for newer comfy versions.

### ISSUE THREAD

**Issue by aravind-h-v** [pydn/ComfyUI-to-Python-Extension#62]
In a recent comfyui version, the function to init custom nodes is changed, this change updates the code for this

https://github.com/pydn/ComfyUI-to-Python-Extension/compare/main...aravindhv10:ComfyUI-to-Python-Extension:fix_for_new_comfy

**Comment by karthikg-09** [comment]
@aravind-h-v Thank you for the fix 🙏

**Comment by pydn** [comment]
Thanks for flagging. Solved with https://github.com/pydn/ComfyUI-to-Python-Extension/pull/70
