### ISSUE TITLE
The script generates incorrect code if name of the custom node contains problematic characters

### ISSUE THREAD

**Issue by PoojanThaker** [pydn/ComfyUI-to-Python-Extension#8]
Hi,

I used the program to generate the python code for the following workflow:

Now unfortunately, the name of the custom node is: "WD14Tagger|pysssss"

This generates the following code:

```
 wd14tagger | pysssss_2 = wd14tagger | pysssss.tag(
                model="wd-v1-4-moat-tagger-v2",
                threshold=0.35,
                character_threshold=0.85,
                exclude_tags="",
                image=get_value_at_index(loadimage_1, 0),
            )
```

The above code doesn't run because it is treated as an OR operator.

```
 wd14tagger | pysssss = NODE_CLASS_MAPPINGS["WD14Tagger|pysssss"]()
    ^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='?
```

**Comment by pydn** [comment]
I'll need to make an update to account for special characters in custom node names. In the meantime can you could remove the spaces and bars in between the variable names in the generated script. For example, wd14tagger | pysssss_2 should be changed to wd14taggerpysssss_2

**Comment by pydn** [comment]
I'll need to make an update to account for special characters in custom node names. In the meantime can you could remove the spaces and bars in between the variable names in the generated script. For example, wd14tagger | pysssss_2 should be changed to wd14taggerpysssss_2. Just be sure to leave the strings inside NODE_CLASD_MAPPINGS as is. Those will need the special characters.

**Comment by PoojanThaker** [comment]
Yup, I renamed the variables and it is working for me now ✌

**Comment by pydn** [comment]
Awesome. I'll circle back here when I get the hotfix in.

**Comment by pydn** [comment]
@PoojanThaker Just pushed a hotfix for this issue. Closing now, but let me know if you run into any issues.
