### ISSUE TITLE
Missing steps in the description? Are we supposed to install comfy with env or conda, instead of using the installer?

### ISSUE THREAD

**Issue by chronoNote** [pydn/ComfyUI-to-Python-Extension#80]
Inside the "Web App Use" description, I followed every step (starting comfy, loading a desired worflow, save it a script dot py, moving it into ComfyUI directory.
then I opened a terminal inside the ComfyUI path, and started the py script:
![image](https://github.com/user-attachments/assets/81b96c43-3d7a-4acc-955d-9f9f4a508dc1)

All libraries are mising of course because I am not in the env.
But installation has an embedded python, it is impossible to go inside that embedded python, is it?

What am I missing again?

**Comment by pydn** [comment]
You need to create a virtual environment and install all requirements for comfyui.

**Comment by chronoNote** [comment]
Oh I see thanks!
I really thought it was straitghforward. That should be written in the description:)
