### ISSUE TITLE
Support New Frontend

### ISSUE THREAD

**Issue by nux1111** [pydn/ComfyUI-to-Python-Extension#82]
Hi, 
Do you plan to support the new comfyui frontend, so we can export python scripts with it?

**Comment by pydn** [comment]
Can you elaborate on what you mean by new comfyui front end? Is the currently implementation not working for you in Comfyui?

**Comment by nux1111** [comment]
@pydn 
![CleanShot 2024-09-27 at 16 01 33@2x](https://github.com/user-attachments/assets/57445c63-5bda-4fdd-aacf-e22247fd38b1)
so this is how comfyui's frontend looks like now. If yours is not like this you might be on the legacy UI. here is the repo for more information. https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by pydn** [comment]
Oh, I see. There are currently no plans to support ComfyUI_frontend. Just ComfyUI.
