### ISSUE TITLE
How can i run the script outside the ComfyUI folder?

### ISSUE THREAD

**Issue by hongmaoxiao** [pydn/ComfyUI-to-Python-Extension#86]
I `Save as Script` for default.py and move it in the /root/ComfyUI folder. 
run `python default.py` It work well.

But I need to build a project, I need to dismantle default.py codes in /root/app folder
And It run in error:

```
ComfyUI found: /root/autodl-tmp/ComfyUI
'/root/autodl-tmp/ComfyUI' added to sys.path
ComfyUI found: /root/autodl-tmp/ComfyUI
Could not import load_extra_path_config from main.py. Looking in utils.extra_config instead.
Could not find the extra_model_paths config file.
ComfyUI found: /root/autodl-tmp/ComfyUI
Traceback (most recent call last):
  File "/root/autodl-tmp/app/default1.py", line 75, in <module>
    import_custom_nodes()
  File "/root/autodl-tmp/app/default1.py", line 63, in import_custom_nodes
    import execution
  File "/root/autodl-tmp/ComfyUI/execution.py", line 13, in <module>
    import nodes
  File "/root/autodl-tmp/ComfyUI/nodes.py", line 21, in <module>
    import comfy.diffusers_load
ModuleNotFoundError: No module named 'comfy.diffusers_load'
```

How can i make it work?
Thanks a lot!

**Comment by hongmaoxiao** [comment]
solved

**Comment by gjnave** [comment]
> I `Save as Script` for default.py and move it in the /root/ComfyUI folder. run `python default.py` It work well.
> 
> But I need to build a project, I need to dismantle default.py codes in /root/app folder And It run in error:
> 
> ```
> ComfyUI found: /root/autodl-tmp/ComfyUI
> '/root/autodl-tmp/ComfyUI' added to sys.path
> ComfyUI found: /root/autodl-tmp/ComfyUI
> Could not import load_extra_path_config from main.py. Looking in utils.extra_config instead.
> Could not find the extra_model_paths config file.
> ComfyUI found: /root/autodl-tmp/ComfyUI
> Traceback (most recent call last):
>   File "/root/autodl-tmp/app/default1.py", line 75, in <module>
>     import_custom_nodes()
>   File "/root/autodl-tmp/app/default1.py", line 63, in import_custom_nodes
>     import execution
>   File "/root/autodl-tmp/ComfyUI/execution.py", line 13, in <module>
>     import nodes
>   File "/root/autodl-tmp/ComfyUI/nodes.py", line 21, in <module>
>     import comfy.diffusers_load
> ModuleNotFoundError: No module named 'comfy.diffusers_load'
> ```
> 
> How can i make it work? Thanks a lot!

how did you do it?
